### ISSUE TITLE
Root Access For Native Modules

### ISSUE THREAD

**Issue by No9** [paddybyers/anode#11]
Hi 
I see there is a requirement to put the addons into 
/data/data/org.meshpoint.anode/app/module/ 
This requires root access to the phone. 
Any idea when it will be resolved or a clue on what prevented the modules being placed on the SDCARD for example? 

Thanks and loved the talk @ LXJS BTW.

**Comment by paddybyers** [comment]
You can install modules into that area with an intent. Put the module onto the sdcard and then do something like

```
adb shell am broadcast -a org.meshpoint.anode.INSTALL -e path /sdcard/<your module>
```

which will put the module into that directory on a non-rooted phone. Have a look in the wiki: 
https://github.com/paddybyers/anode/wiki/Modules

If you want to be able to load modules from the sdcard, then it should just work by specifying the absolute path and doing a require().

Alternatively you could rebuild the app and change the hard-coded NODE_PATH to include the location(s) you want.

**Comment by No9** [comment]
Thanks @paddybyers both options worked as I found the location of the NodePath in RuntimeNative.java
