### ISSUE TITLE
build bridge failed(no setExitHandler) on 'master-isolate-android'

### ISSUE THREAD

**Issue by karfield** [paddybyers/anode#22]
some errors came out when I checked out 'master-isolate-android' :

$ ndk-build NDK_PROJECT_PATH=. NDK_APPLICATION_MK=Application.mk

Install        : libjninode.so => libs/armeabi/libjninode.so
Compile++ thumb  : bridge <= Env.cpp
bridge/src/Env.cpp: In member function 'int bridge::Env::initV8()':
bridge/src/Env.cpp:142:16: error: 'class node::Isolate' has no member named 'setExitHandler'
make: **\* [obj/local/armeabi/objs/bridge/src/Env.o] Error 1

**Comment by paddybyers** [comment]
That branch was intended to track master but is now a long long way from master and it doesn't really serve any useful purpose. Use `v0.6-android`.

**Comment by karfield** [comment]
thx!
