### ISSUE TITLE
Thread pooling not working in libuv, calling uv_run(uv_default_loop()) fixes

### ISSUE THREAD

**Issue by skabbes** [paddybyers/anode#7]
When compiling [node-sqlite3](https://github.com/developmentseed/node-sqlite3) for anode, db connections weren't being successfully opened.  Investigating further, it seemed that the the "after" callback in `uv_queue_work` wasn't being called.  Adding `uv_run(uv_default_loop())` fixes both this test code **and** the sqlite code.

This code shows the error:

``` c++

#include <node.h>
#include <v8.h>
#include <android/log.h>

#define APPNAME "HELLOWORLD"

using namespace v8;

static int timesFinished = 0;

void AsyncWork(uv_work_t* req) {
    __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "In Async Work");
    timesFinished++;
}

void AfterAsync(uv_work_t* req) {
    __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "Finished Async Work");
    timesFinished++;

    // be nice and clean up
    delete req;
    req = NULL;
}

Handle<Value> Method(const Arguments& args) {
  HandleScope scope;

  uv_work_t * req = new uv_work_t();
  int status = uv_queue_work(uv_default_loop(), req, AsyncWork, AfterAsync);
  __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "uv_queue_work status %d", status);

  // I Shouldn't have to call this... but calling it fixes this code AND SQLITE3
  uv_run(uv_default_loop());

  __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "work count should be 2 %d", timesFinished);

  return scope.Close(String::New("something worked"));
}

void init(Handle<Object> target) {
  target->Set(String::NewSymbol("test"), FunctionTemplate::New(Method)->GetFunction());
}


NODE_MODULE(asyncfail, init)
```

It would appear that libuv's event loop (?) isn't being started, and this problem would be fixed by adding a call to `uv_run(...)` in the initialization somewhere.

**Comment by paddybyers** [comment]
Thanks for looking at this. I'm sure it's wrong to call `uv_default_loop()` because it needs to be the loop associated with the specific request, but I'll have a look.

**Comment by skabbes** [comment]
I don't know how to use libuv by any means (not at all), but perhaps the default loop should be started by the system, but any other loop it is the user's job to start it by hand.  Here is the [test case](https://github.com/paddybyers/node/blob/v0.6-android/deps/uv/test/test-threadpool.c) in libuv, which is how i figured out to start the looper in the first place.

However, [this](https://github.com/developmentseed/node-sqlite3/blob/master/src/database.cc) is the code in node-sqlite3 which works on mac, but stalls on android.  Particularly the `Database::Work_AfterOpen` function is never called.

Hope this helps...

**Comment by skabbes** [comment]
I think the way that you're doing it now is fine, however, the isolate we create is never `node::defaultIsolate`, so therefore `uv_run` is never called on the default loop.  It is called correctly on that isolate's particular loop.  In theory, this is fine, but or addons who rely on `uv_default_loop` being run will never work correctly.  Addons I've looked at exclusively use `uv_default_loop`.

Perhaps the best way to fix this is to bind to `node::defaultIsolate` the first time we "boot up" a node instance.  Thoughts?

Check out `node::Start` and `node::Isolate::Start` in [node.cc](https://github.com/paddybyers/node/blob/v0.6-android/src/node.cc) to see the logic around starting event loops.

**Comment by paddybyers** [comment]
Addons can't use uv_default_loop(); they should only deliver events to the loop that they are initialised for.

If they deliver an event to the default loop and that event ends up calling into JS, then either it will crash  - because they are passing objects that do not belong to the default Isolate - or their events will end up doing nothing because whatever happened in that default isolate has no connection with the calling application (which is in a different isolate).

So if sqlite is calling uv_default_loop(),  then it is broken IMO, at least in a universe of multiple isolates.

**Comment by skabbes** [comment]
Ya, this is a bug in node-sqlite3 as well as bcrypt, naming 2 big ones.  I'll see if I can submit patches to them so long as no standard api's are broken.
